### ISSUE TITLE
Moving hardware ID's to Constant class.

### ISSUE THREAD

**Issue by mrhelland** [1359Scalawags/2020Robot#3]
A: Climb
M: Ball
D: Drive

**Comment by SnipershotUS** [comment]
Ball and Control Panel Constants are done

**Comment by SnipershotUS** [comment]
Ball, Drive, Control Panel, and Climb Subsystem Constants are done

**Comment by WildstrikePlayz** [comment]
ClimbSystem Constants are done!  : )
